server:
  port: 8083

spring:
  application:
    name: audit-event-service
  kafka:
    bootstrap-servers: ${CARELITE_KAFKA_BOOTSTRAP_SERVERS:pkc-oxqxx9.us-east-1.aws.confluent.cloud:9092}
    client-id: ${CARELITE_KAFKA_CLIENT_ID:audit-event-service}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${CARELITE_KAFKA_API_KEY:}' password='${CARELITE_KAFKA_API_SECRET:}';"
      session.timeout.ms: 45000
      spring.json.trusted.packages: com.carelite.events

management:
  endpoints:
    web:
      exposure:
        include: health,info
